DROP TABLE IF EXISTS foto CASCADE;
DROP TABLE IF EXISTS produto CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;

CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    id_categoria BIGINT NOT NULL, -- Coluna id_categoria explícita
    preco NUMERIC(38,2),
    preco_promocional NUMERIC(38,2), -- Adicionado se existir no seu modelo ou dados
    estoque INTEGER,
    fabricante VARCHAR(50) NOT NULL,
    ativo BOOLEAN,
    data_cadastro DATE,
    data_atualizacao DATE,
    FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);

CREATE TABLE foto (
    id_foto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255), -- Agora armazena o nome do arquivo (sem tipo e dados binários)
    id_produto BIGINT,
    FOREIGN KEY (id_produto) REFERENCES produto(id)
); 